# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQt1U8fkgHLSKQPmCWlWO7-rqZWffZ7c
"""

import torch
from torch.utils.data import DataLoader, Dataset
from transformers import XLMRobertaTokenizer, XLMRobertaForSequenceClassification
from transformers import get_linear_schedule_with_warmup
from torch.optim import AdamW
from tqdm import tqdm

# Tokenizer
tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')

def tokenize(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=128)

train_encodings = tokenize({"text": train_df["text"].tolist()})
val_encodings   = tokenize({"text": val_df["text"].tolist()})
test_encodings  = tokenize({"text": test_df["text"].tolist()})

train_labels = torch.tensor(train_df["label"].values)
val_labels   = torch.tensor(val_df["label"].values)
test_labels  = torch.tensor(test_df["label"].values)

# Model
num_labels = df["label"].nunique()
model = XLMRobertaForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    num_labels=num_labels
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
print(f"moved to {device}")

# Dataset class
class MultiLingualDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encoding = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encoding.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Dataloaders
train_dataset = MultiLingualDataset(train_encodings, train_labels)
val_dataset   = MultiLingualDataset(val_encodings, val_labels)
test_dataset  = MultiLingualDataset(test_encodings, test_labels)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=16, shuffle=False)
test_loader  = DataLoader(test_dataset, batch_size=16, shuffle=False)

# Optimizer & scheduler
optimizer = AdamW(model.parameters(), lr=2e-5)

epochs = 3
total_steps = len(train_loader) * epochs

scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

# Training function
def train_epoch(model, loader, optimizer, scheduler):
    model.train()
    total_loss = 0

    for batch in tqdm(loader):
        batch = {k: v.to(device) for k, v in batch.items()}
        optimizer.zero_grad()

        outputs = model(**batch)
        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        optimizer.step()
        scheduler.step()

    return total_loss / len(loader)

# Evaluation function
def eval_epoch(model, loader):
    model.eval()
    total_loss = 0

    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)
            loss = outputs.loss
            total_loss += loss.item()

    return total_loss / len(loader)

# Training loop
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")

    train_loss = train_epoch(model, train_loader, optimizer, scheduler)
    val_loss   = eval_epoch(model, val_loader)

    print(f"Train_loss {train_loss:.4f}")
    print(f"val_loss   {val_loss:.4f}")